import torch
from transformers import AutoTokenizer, AutoModelForCausalLM
import re

def svd_weight(param, r):
    U, S, Vh = torch.svd(param)
    U_r = U[:, :r]          
    S_r = torch.diag(S[:r]) 
    Vh_r = Vh[:, :r]        
    return U_r @ S_r, Vh_r


def trans_weight_specific(slm, llm, layer_mapping, r=8, key_parameters=["q_proj","v_proj","k_proj","o_proj","gate_proj","down_proj","up_proj"]):
    """
    Calculates the transformation matrices (Wu, Wv) between specific SLM and LLM layers.
    
    Args:
        slm: The small language model.
        llm: The large language model.
        layer_mapping (dict): A dictionary mapping SLM layer indices to LLM layer indices 
                              (e.g., {0: 4, 1: 5, 2: 6} maps SLM layers 0-2 to LLM layers 4-6).
        r (int): SVD rank.
        key_parameters (list): List of parameter names to transform.
    """
    params_llm = llm.state_dict()
    dict_trans = {}
    
    for name, param_slm in slm.named_parameters():
        if "layer" in name and any(name_lora in name for name_lora in key_parameters) and "weight" in name:
            layer_num_match = re.search(r'layers\.(\d+)\.', name)
            if not layer_num_match:
                continue
                
            layer_num = int(layer_num_match.group(1))
            
            # Only process if this specific SLM layer is in our mapping
            if layer_num in layer_mapping:
                llm_layer_num = layer_mapping[layer_num]
                
                # Safely replace the layer number in the parameter name
                name_llm = name.replace(f"layers.{layer_num}.", f"layers.{llm_layer_num}.", 1)
                
                if name_llm in params_llm:
                    param_llm = params_llm[name_llm]
                    
                    slm_U, slm_V = svd_weight(param_slm, r)  ## m,n to mxr, nxr
                    llm_U, llm_V = svd_weight(param_llm, r)
                    
                    Wu = llm_U @ torch.linalg.pinv(slm_U)  
                    Wv = llm_V @ torch.linalg.pinv(slm_V)  
                    
                    dict_trans[name_llm] = (Wu, Wv)
                    print(f"Calculated transform: SLM {name} -> LLM {name_llm}")
                    
    return dict_trans


def trans_lora_weight_specific(slm, slmfinetune, uv_trans, layer_mapping, r=8, key_parameters=["q_proj","v_proj","k_proj","o_proj","gate_proj","down_proj","up_proj"]):
    """
    Applies the transformation matrices to the finetuned LoRA delta weights.
    
    Args:
        slm: The base small language model.
        slmfinetune: The fine-tuned small language model.
        uv_trans (dict): Transformation matrices generated by trans_weight_specific.
        layer_mapping (dict): The exact same layer mapping used in trans_weight_specific.
        r (int): SVD rank.
        key_parameters (list): List of parameter names to transform.
    """
    lora_init = {}
    params_slmfinetune = slmfinetune.state_dict()
    
    for name, param in slm.named_parameters():
        if "layer" in name and any(name_lora in name for name_lora in key_parameters) and "weight" in name:
            layer_num_match = re.search(r'layers\.(\d+)\.', name)
            if not layer_num_match:
                continue
                
            layer_num = int(layer_num_match.group(1))
            
            # Check if this layer is part of our specific mapping
            if layer_num in layer_mapping:
                llm_layer_num = layer_mapping[layer_num]
                name_llm = name.replace(f"layers.{layer_num}.", f"layers.{llm_layer_num}.", 1)
                
                if name_llm in uv_trans:
                    param_delta = params_slmfinetune[name] - param
                    delta_U, delta_V = svd_weight(param_delta, r)  ## m,n to mxr, nxr
                    
                    u_trans, v_trans = uv_trans[name_llm]
                    u_lora = u_trans @ delta_U  ## u_lora: Mxr
                    v_lora = v_trans @ delta_V  ## v_lora: Nxr
                    
                    lora_init[name_llm] = (u_lora, v_lora)
                    print(f"Transferred LoRA: SLM {name} -> LLM {name_llm}") 
    return lora_init


def trans_weight_top(slm, llm, r=8, key_parameters=["q_proj","v_proj","k_proj","o_proj","gate_proj","down_proj","up_proj"]):
    if len(llm.model.layers) > len(slm.model.layers):
        layer_site = len(llm.model.layers) - len(slm.model.layers)
        params_llm = llm.state_dict()
        dict_trans = {}
        for name, param in slm.named_parameters():
            if "layer" in name and any(name_lora in name for name_lora in key_parameters) and "weight" in name:
                param_slm = param
                layer_num = int(re.search(r'layers\.(\d+)\.', name).group(1))
                name_llm = name.replace(str(layer_num), str(layer_num+layer_site), 1)
                param_llm = params_llm[name_llm]
                slm_U, slm_V = svd_weight(param_slm, r)  ## m,n to mxr, nxr
                llm_U, llm_V = svd_weight(param_llm, r)
                Wu = llm_U @ torch.linalg.pinv(slm_U)  
                Wv = llm_V @ torch.linalg.pinv(slm_V)  
                dict_trans[name_llm] = (Wu, Wv)
                print(name)
    else:
        layer_site = len(slm.model.layers) - len(llm.model.layers)
        params_slm = slm.state_dict()
        dict_trans = {}
        for name, param, in llm.named_parameters():
            if "layer" in name and any(name_lora in name for name_lora in key_parameters) and "weight" in name:
                param_llm = param
                layer_num = int(re.search(r'layers\.(\d+)\.', name).group(1))
                name_slm = name.replace(str(layer_num), str(layer_num+layer_site), 1)
                param_slm = params_slm[name_slm]
                slm_U, slm_V = svd_weight(param_slm, r)  ## m,n to mxr, nxr
                llm_U, llm_V = svd_weight(param_llm, r)
                Wu = llm_U @ torch.linalg.pinv(slm_U)  ## 
                Wv = llm_V @ torch.linalg.pinv(slm_V)  ## 
                dict_trans[name] = (Wu, Wv)
                print(name)
    return dict_trans


def trans_lora_weight_top(slm, slmfinetune, uv_trans, r=8, key_parameters=["q_proj","v_proj","k_proj","o_proj","gate_proj","down_proj","up_proj"]):
    llm_layers = int(re.search(r'layers\.(\d+)\.', next(reversed(uv_trans))).group(1))+1
    lora_init = {}
    params_slmfinetune = slmfinetune.state_dict()
    if llm_layers > len(slm.model.layers):
        layer_site = llm_layers - len(slm.model.layers)
        for name, param in slm.named_parameters():
            if "layer" in name and any(name_lora in name for name_lora in key_parameters) and "weight" in name:
                print(name)
                layer_num = int(re.search(r'layers\.(\d+)\.', name).group(1))
                name_llm = name.replace(str(layer_num), str(layer_num+layer_site), 1)
                param_delta = params_slmfinetune[name] - param
                delta_U, delta_V = svd_weight(param_delta, r)  ## m,n to mxr, nxr
                u_trans, v_trans = uv_trans[name_llm]
                u_lora = u_trans @ delta_U  ## u_lora: Mxr
                v_lora = v_trans @ delta_V  ## v_lora: Nxr
                lora_init[name_llm] = (u_lora, v_lora)
    else:
        layer_site = len(slm.model.layers) - llm_layers
        for name, param in slm.named_parameters():
            if "layer" in name and  any(name_lora in name for name_lora in key_parameters) and "weight" in name:
                layer_num = int(re.search(r'layers\.(\d+)\.', name).group(1))
                if layer_num >= layer_site:
                    print(name)
                    param_delta = params_slmfinetune[name] - param
                    delta_U, delta_V = svd_weight(param_delta, r)  ## m,n to mxr, nxr
                    name_llm = name.replace(str(layer_num), str(layer_num-layer_site), 1)
                    u_trans, v_trans = uv_trans[name_llm]
                    u_lora = u_trans @ delta_U  ## u_lora: Mxr
                    v_lora = v_trans @ delta_V  ## v_lora: Nxr
                    lora_init[name_llm] = (u_lora, v_lora)        
    return lora_init


path_slm = '/models/Qwen2.5-0.5B-Instruct/'  ## Qwen2.5-0.5B: 24 layers, Qwen2.5-3B: 36 layers, Qwen2.5-7B: 28 layers, Qwen2.5-1.5B: 28 layers, Qwen2.5-14B: 48 layers
path_llm = '/models/Llama-3.2-3B-Instruct/'  ## 28 layers
path_llm = '/data/yakun_data/A-mem/models/Phi-3-small-8k-instruct/' 
model_llm = AutoModelForCausalLM.from_pretrained(path_llm, trust_remote_code=True)
model_slm = AutoModelForCausalLM.from_pretrained(path_slm, trust_remote_code=True)

trans_slm2llm = trans_weight_top(model_slm, model_llm, r=8)
print("Trans Done!")
torch.save(trans_slm2llm, "weight_trans/qwen2505b23b.pth")


path_slmfinetune = '/PiSSA/output/mmlu-fpft-Qwen-25-05b-full/'
model_slmfinetune = AutoModelForCausalLM.from_pretrained(path_slmfinetune)
uv_trans = torch.load("weight_trans/qwen2505b23b.pth")
lora_init = trans_lora_weight_top(model_slm, model_slmfinetune, uv_trans)
print("Init Done!")
torch.save(lora_init, "weight_trans/svd_r8_mmlu_qwen2505b23b.pth")
